"""Sensitive Data Detection & Compliance Assistant — Streamlit UI."""

import os

import pandas as pd
import streamlit as st

from src import audit
from src.ai_engine import answer_question, generate_summary, llm_available
from src.detector import detect, summarize_findings
from src.extractor import ExtractionError, extract_text
from src.redactor import redact_text
from src.risk import classify

st.set_page_config(
    page_title="Sensitive Data & Compliance Assistant",
    page_icon="🛡️",
    layout="wide",
)

RISK_STYLE = {
    "High Risk": ("🔴", "#c0392b"),
    "Medium Risk": ("🟠", "#e67e22"),
    "Low Risk": ("🟢", "#27ae60"),
}


def _init_state():
    st.session_state.setdefault("documents", {})   # filename -> analysis dict
    st.session_state.setdefault("chat", [])        # list of {role, content}


def analyze_file(uploaded_file) -> dict | None:
    file_bytes = uploaded_file.getvalue()
    try:
        text = extract_text(file_bytes, uploaded_file.name)
    except ExtractionError as exc:
        st.error(f"**{uploaded_file.name}**: {exc}")
        return None

    findings = detect(text)
    risk = classify(findings)
    masked = redact_text(text, findings, mode="mask")
    redacted = redact_text(text, findings, mode="redact")
    summary, summary_mode = generate_summary(findings, risk, masked, uploaded_file.name)

    audit.log_event(
        "document_scanned",
        filename=uploaded_file.name,
        sha256=audit.file_sha256(file_bytes),
        size_bytes=len(file_bytes),
        risk_level=risk["level"],
        risk_score=risk["score"],
        findings_total=len(findings),
        findings_by_type={label: info["count"]
                          for label, info in summarize_findings(findings).items()},
    )

    return {
        "text": text,
        "findings": findings,
        "risk": risk,
        "masked": masked,
        "redacted": redacted,
        "summary": summary,
        "summary_mode": summary_mode,
    }


def render_document(name: str, doc: dict):
    risk = doc["risk"]
    icon, color = RISK_STYLE[risk["level"]]

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Risk Level", f"{icon} {risk['level']}")
    c2.metric("Risk Score", risk["score"])
    c3.metric("Total Findings", risk["total_findings"])
    c4.metric("High-Severity", risk["by_severity"]["HIGH"])
    st.markdown(
        f"<div style='border-left:4px solid {color}; padding:0.5em 1em; "
        f"background:rgba(128,128,128,0.08); border-radius:4px;'>"
        f"{risk['explanation']}</div>",
        unsafe_allow_html=True,
    )

    tab_findings, tab_summary, tab_redacted, tab_raw = st.tabs(
        ["🔍 Findings", "📋 Compliance Summary", "🕶️ Redacted Copy", "📄 Extracted Text"]
    )

    with tab_findings:
        if not doc["findings"]:
            st.success("No sensitive data detected.")
        else:
            agg = summarize_findings(doc["findings"])
            st.dataframe(
                pd.DataFrame([
                    {"Entity": label, "Count": info["count"],
                     "Severity": info["severity"],
                     "Masked examples": ", ".join(info["examples"])}
                    for label, info in sorted(agg.items(), key=lambda kv: -kv[1]["count"])
                ]),
                use_container_width=True, hide_index=True,
            )
            with st.expander("Detailed findings (masked, with context)"):
                st.dataframe(
                    pd.DataFrame([
                        {"Type": f.label, "Masked value": f.masked,
                         "Severity": f.severity, "Confidence": f"{f.confidence:.0%}",
                         "Context": f.context}
                        for f in doc["findings"]
                    ]),
                    use_container_width=True, hide_index=True,
                )

    with tab_summary:
        if doc["summary_mode"] == "offline":
            st.caption("Generated by the built-in rule engine "
                       "(set GEMINI_API_KEY for LLM-written narratives).")
        else:
            st.caption("Generated by Gemini from the *redacted* document — "
                       "raw sensitive values never leave this machine.")
        st.markdown(doc["summary"])

    with tab_redacted:
        mode = st.radio("Redaction style", ["Partial masking", "Full redaction"],
                        horizontal=True, key=f"redact_mode_{name}")
        content = doc["masked"] if mode == "Partial masking" else doc["redacted"]
        st.download_button("⬇️ Download sanitized copy", content,
                           file_name=f"REDACTED_{name}.txt", key=f"dl_{name}")
        st.text_area("Sanitized document", content, height=350,
                     key=f"redacted_view_{name}")

    with tab_raw:
        st.warning("This tab shows the original extracted text, including "
                   "sensitive values. Visible locally only.")
        st.text_area("Extracted text", doc["text"], height=350,
                     key=f"raw_view_{name}")


def main():
    _init_state()

    st.title("🛡️ Sensitive Data Detection & Compliance Assistant")
    st.caption(
        "Upload PDF / TXT / CSV documents → detect PII, credentials and "
        "confidential content → classify risk → get a compliance report → "
        "ask questions."
    )

    with st.sidebar:
        st.header("📤 Upload documents")
        uploads = st.file_uploader(
            "PDF, TXT or CSV", type=["pdf", "txt", "csv"],
            accept_multiple_files=True,
        )
        if uploads:
            for up in uploads:
                if up.name not in st.session_state.documents:
                    with st.spinner(f"Scanning {up.name}…"):
                        result = analyze_file(up)
                    if result:
                        st.session_state.documents[up.name] = result

        st.divider()
        st.subheader("⚙️ Engine status")
        if llm_available():
            st.success("AI mode: Gemini connected")
        else:
            st.info("AI mode: offline rule engine\n\n"
                    "Set `GEMINI_API_KEY` to enable LLM summaries & free-form Q&A.")

        if st.session_state.documents:
            st.divider()
            if st.button("🗑️ Clear all documents"):
                st.session_state.documents = {}
                st.session_state.chat = []
                st.rerun()

        st.divider()
        with st.expander("🧾 Audit log"):
            records = audit.read_log(limit=20)
            if records:
                for r in reversed(records):
                    st.caption(
                        f"`{r['timestamp'][:19]}` **{r['event']}** — "
                        f"{r.get('filename', r.get('question', ''))}"
                    )
            else:
                st.caption("No events yet.")

    docs = st.session_state.documents
    if not docs:
        st.info("⬅️ Upload one or more documents in the sidebar to begin. "
                "Sample documents are included in the `sample_docs/` folder.")
        return

    # ---- Multi-document overview -----------------------------------------
    if len(docs) > 1:
        st.subheader("📚 Document overview")
        st.dataframe(
            pd.DataFrame([
                {"Document": n, "Risk": d["risk"]["level"],
                 "Score": d["risk"]["score"],
                 "Findings": d["risk"]["total_findings"]}
                for n, d in docs.items()
            ]),
            use_container_width=True, hide_index=True,
        )

    selected = st.selectbox("Select document", list(docs.keys()))
    render_document(selected, docs[selected])

    # ---- Q&A ---------------------------------------------------------------
    st.divider()
    st.subheader("💬 Ask about this document")
    st.caption('Try: "What sensitive data exists in the document?" · '
               '"How many email addresses are present?" · '
               '"What compliance risks are identified?" · "Summarize this document."')

    for msg in st.session_state.chat:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    if question := st.chat_input("Ask a question about the selected document…"):
        st.session_state.chat.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)

        doc = docs[selected]
        with st.chat_message("assistant"):
            with st.spinner("Thinking…"):
                answer, mode = answer_question(
                    question, doc["findings"], doc["risk"],
                    doc["masked"], selected,
                )
            st.markdown(answer)
            st.caption(f"answer source: {mode}")

        st.session_state.chat.append({"role": "assistant", "content": answer})
        audit.log_event("question_asked", filename=selected,
                        question=question[:200], answer_mode=mode)


if __name__ == "__main__":
    main()
